apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scotch-dep
  labels:
    #Project ID
    app: scotch-155622
spec:
  #Run two instances of our application
  replicas: 2
  template:
    metadata:
      labels:
        app: scotch-155622
    spec:
      #Container details
      containers:
        - name: node-app
          image: gcr.io/scotch-155622/node-app:0.0.1
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 8000
          
          env:
          # Name of the environment variable as will be in the Pod
            - name: IG_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-secret
                    # key of the value stored in the secret
                    key: access_token
          livenessProbe:
              httpGet:
                  path: /health_check
                  port: 8000
              # Delay the first probe by 15 seconds
              initialDelaySeconds: 15
              # Probe the server every 5 seconds
              periodSeconds: 10
              # Timeout with error after one second if no response is given
              timeoutSeconds: 1